title: Fruit or Vegetable?
author:
  name: Matthew Miner
  email: mminer237@gmail.com
  site: https://matthewminer.name
url: https://fruitorvegetable.science
sourceUrl: https://github.com/mminer237/fruitorvegetable
tagManagerCode: GTM-5XJ2H43
googleAdClient: ca-pub-5576042369154755
themeColor: "#dc4d66"

# googleFonts:
#   - Lato:400,400i,900
#   - Old+Standard+TT:400,400i,700
#   - IBM+Plex+Serif:500,500i

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "items"
    values:
      layout: "item"
  -
    scope:
      path: ""
      type: "types"
    values:
      layout: "type"

include: [_redirects]

incremental: true

collections:
  pages:
    output: true
    permalink: /:path
  items:
    output: true
    permalink: /:path
  types:
    output: true
    permalink: /:path

sass:
  style: compressed

plugins:
  - jekyll-responsive-image
  - jekyll-sitemap

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 700
    - width: 126
  auto_rotate: true